name: My First Pipeline

# 1. THE TRIGGER: Run this whenever I push code
on: [push]

# The New Lint job ( to detect syntax error early
jobs: 
  lint-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install yamillint
        uses: sudo apt-get install -y yamllint

      - name: Run lint check
        uses: yamllint .github/workflows/hello-world.yml
        
# 2. THE MISSION: What should happen?
jobs:
  say-hello:
    runs-on: ubuntu-latest  # Use a fresh Linux machine provided by GitHub
    needs: lint-yaml 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Step 1: Grab my code files

      - name: Send a message
        run: echo "Hello! My first GitHub Action is running successfully."

      - name: Show the Date
        run: date
        
      - name: Testing Secrets
        run: echo "My secret key is ${{ secrets.MY_AWS_KEY }}"
        
      - name: Lint Test
        run: echo "Lint passed. I'm running now!"
